### ISSUE TITLE
Can Ripple use without Nuxt?

### ISSUE THREAD

**Issue by joseph-so** [dpc-sdp/ripple#318]
Can Ripple use without Nuxt? (e.g. use directly in Client side)
if yes, what do I need to pass to the Vue.use ?

**Comment by tim-yao** [comment]
@joseph-so Hope it's not too late, it can be used without Nuxt. 

Our storybook is an example.
Install Ripple global plugin: https://github.com/dpc-sdp/ripple/blob/v1.0.0-alpha.72/.storybook/config.js#L14

Global options are here if you need to customize them: https://github.com/dpc-sdp/ripple/blob/v1.0.0-alpha.72/packages/Atoms/Global/index.js#L5

You probably use it like this:
```
import Vue from 'vue'
import RplGlobal from '@dpc-sdp/ripple-global'
Vue.use(RplGlobal, { hostname: 'www.yourdomain.com' }}```

**Comment by dylankelly** [comment]
Hi @joseph-so, do you mind describing your use case for ripple without Nuxt, so we might be able to provide better information? Otherwise I will close this issue.

**Comment by joseph-so** [comment]
@tim-yao Thanks for it, I will have a try.

@dylankelly,
  I would like to the Rupple directly in my Vue Project, but I do not want to set up the Nuxt. I want to see if it is possible to use Ripple similar to Vuetify. If it can, that will be good

**Comment by mj-hardy** [comment]
Hi @tim-yao  and @dylankelly and @joseph-so , Is these any update on this? Tim, how did you go. I have a similar use case. I want to build a quick prototype and use the ripple components but don't want to go through the full process of setting up nuxt as yet another frmaework

**Comment by joseph-so** [comment]
@mj-hardy 
sorry to reply you late. (Did not get any email - may be in spam). I still cannot figure out how I can use it directly like Vuetify

**Comment by joseph-so** [comment]
@mj-hardy 
  I just do the other test, yes, it is possible to use it without Nuxt based on the updated manual. I just have some minor issue to integrate with other CMS or if I want to have some defined code in the HTML div area

**Comment by joseph-so** [comment]
Yes, just find it is working in general (just has some minor issue). Will open the other comment instead
