### ISSUE TITLE
Using hidden inputs in rpl-form leaves margin

### ISSUE THREAD

**Issue by danlaush** [dpc-sdp/ripple#325]
Hi Ripplers,

When we use `rpl-form` to add a hidden input field to the page, the resulting HTML+CSS leaves a phantom margin attached to the empty `.field-group`. 

This can also be seen on https://vic.gov.au/ at the bottom of the page in `AppContentRating`.

![Screen Shot 2019-04-10 at 3 15 59 pm](https://user-images.githubusercontent.com/1204500/55853252-950d8980-5ba3-11e9-852f-5033cbf6daef.png)

**Comment by danlaush** [comment]
If vue-form-generator has hooks available for this, could a class be applied to the form-group of the hidden field? Then the margin could be applied only when the input isn't hidden.

Alternative solution, could the margins be applied to the form elements directly? input[hidden] is display:none; so the margin would disappear.

**Comment by tim-yao** [comment]
Hi @danlaush It's possible to add class on the `.form-group` element, see an example here: https://github.com/dpc-sdp/ripple/blob/master/src/storybook-components/_data/demoData.js#L1042

**Comment by danlaush** [comment]
Excellent, thanks @tim-yao.

```
styleClasses: ['rpl-visually-hidden']
```
👌
