### ISSUE TITLE
Would like to add custom SVGs to RplIcon

### ISSUE THREAD

**Issue by danlaush** [dpc-sdp/ripple#355]
Our designs require the use of SVGs not available in the icon library.

We are using `RplIcon` where we can, but would lose the benefit of it if we can't add our icons to the sprite.

I would need to be able to pass `RplIcon` an SVG file as a prop, instead of a string.

```html
<template>
  <div class="my-header">
    <rpl-icon
          :symbol="customHamburger"
          color="white"
          size="0.8"
          class="logo-bar__search-icon"
        />
  </div>
</template>

<script>
import { RplIcon } from '@dpc-sdp/ripple-icon'
import customHamburger from '~/assets/icons/customHamburger.svg'

export default {
  name: 'MyHeader',
  components: {
    RplIcon
  },
  data: {
    customHamburger
  }
}
</script>
```

**Comment by tim-yao** [comment]
This has been implemented. Docs here: https://github.com/dpc-sdp/ripple/tree/master/packages/ripple-nuxt-tide#custom-icons
