### ISSUE TITLE
Webform conditional logic

### ISSUE THREAD

**Issue by febdao** [dpc-sdp/ripple#595]
Hi there,
I worked on a project which was required the users can conditionally see different fields options on a webform such that I can work through different scenarios to seek the information relevant to them likes this: http://www.asbestos.vic.gov.au/about-asbestos/managing-asbestos/working-safely-with-asbestos

The AppForm component uses the conditional logic function to control states and validation on fields.
testField() currently only supports the 'required' state, but should also have:

```
- visible
- hidden
- enabled
- disabled
```

So I implemented it and created a pull request here: https://github.com/dpc-sdp/ripple/pull/594
Could someone please review and merge my PR?

Thank you!

**Comment by tim-yao** [comment]
Thanks @febdao for your contributing, I have merged your PR into PR #600 which will be merged soon.
