### ISSUE TITLE
Axios POST - remove base url variable.

### ISSUE THREAD

**Issue by alan-cole** [dpc-sdp/ripple#706]
For post requests in tide, we are setting the axios config `baseUrl`.

https://github.com/dpc-sdp/ripple/blob/master/packages/ripple-nuxt-tide/lib/core/tide.js#L80

Based on the [axios readme](https://www.npmjs.com/package/axios), `baseURL` is the correct variable name, so the `baseUrl` variable is not being properly set.
However, if the correct variable name was used and the base was being set to `config.baseUrl`, it would break form submissions, as submitting directly to the base URL from a browser would result in a CORS error.

The line should be removed as it's redundant.

**Comment by tim-yao** [comment]
Thanks @alan-cole. You are right. A PR is welcome, otherwise I will do it.

**Comment by alan-cole** [comment]
Thanks @tim-yao - Raised a PR.

https://github.com/dpc-sdp/ripple/pull/707

**Comment by simesy** [comment]
> However, if the correct variable name was used and the base was being set to config.baseUrl, it would break form submissions, as submitting directly to the base URL from a browser would result in a CORS error.

We want to be able to configure the backend endpoint, and understand the CORS implications, so please fix it rather than removing it.
