### ISSUE TITLE
What browsers do you aim to support?

### ISSUE THREAD

**Issue by rooby** [dpc-sdp/ripple#77]
What browsers do you aim to support?

This would be useful information to add to the contributing docs.

**Comment by tim-yao** [comment]
Hey @rooby Below is the original target made one year ago, we may review them soon.

**Browser Compatibility**
Desktop
Chrome 10+, Firefox 4+, Safari 5+, Opera 12+, IE 10+ 

Mobile
Safari for I0S 3+, Android 2+, Chrome for Android and IOS 4+, Firefox for Android, IE 10+ for Windows 8 devices

As this is a Vue.js project, so the JS supports all browsers that are [ES5-compliant](http://kangax.github.io/compat-table/es5/) (IE8 and below are not supported) 

We will update the doc to add the "Browser Compatibility". Thanks for your help!
