### ISSUE TITLE
Storybook knob titled "Link" should be "Image"

### ISSUE THREAD

**Issue by alan-cole** [dpc-sdp/ripple#822]
https://github.com/dpc-sdp/ripple/blob/master/packages/components/Molecules/Card/stories.js#L68

Storybook knob for Card Image Navigation component reads "Link", though it's for the "Image" property.

**Comment by tim-yao** [comment]
@rubyllamadora does that relates to the storybook `control` work you are doing now?

**Comment by rubyllamadora** [comment]
> @rubyllamadora does that relates to the storybook `control` work you are doing now?

Yes. This should go away once we implement control addon.
